### ISSUE TITLE
Shader issue in linux

### ISSUE THREAD

**Issue by ennob** [SebLague/Geographical-Adventures#31] opened 2022-05-02 14:24 UTC
The game runs flawlessly except for a visual glitch. Not sure what could be causing it but it almost seems like something was rotated 180 degrees.
![Screenshot from 2022-05-02 15-19-11](https://user-images.githubusercontent.com/14582434/166250412-f3628df7-90ac-49b5-b901-1e7d587b9477.png)

**Comment by ADIOP55550** [comment] 2022-05-02 14:56
Happens to me too, in the evening it turns purple so it is the feature from the last video

**Comment by ADIOP55550** [comment] 2022-05-02 14:57
Duplicate of #28

**Closed** 2022-05-02 16:43 UTC
