### ISSUE TITLE
Spanish translation not loading correctly

### ISSUE THREAD

**Issue by tposejank** [SebLague/Geographical-Adventures#85] opened 2022-05-14 04:37 UTC
![image](https://user-images.githubusercontent.com/81495861/168410087-2a51d540-cf9b-49a9-a516-df186b20dc4c.png)
(menu)
![image](https://user-images.githubusercontent.com/81495861/168410843-e2cb1e12-9e25-42f7-acc2-0f50deb41838.png)
(map)
![image](https://user-images.githubusercontent.com/81495861/168410845-65795654-ef3a-4134-bf8b-707ac45bd20b.png)
(game)

**Comment by SebLague** [comment] 2022-05-14 18:21
Thanks for letting me know! Not sure how that happened, but will fix soon.

**Comment by SebLague** [comment] 2022-05-29 20:43
Hey, I'm very sorry it took me so long to get around to updating the builds, but just wanted to let you know that the issue is now fixed.

**Closed by SebLague** 2022-05-29 20:43 UTC
